### ISSUE TITLE
Fermilab street address

### ISSUE THREAD

**Issue by kadrlica** [kpedro88/FNAL_ECA_Proposal_Template#2]
I think it should "Kirk Rd. and Pine St." rather than "Kirk and Pine St." (more commonly I hear: "Pine St. and Kirk Rd.").

**Comment by kpedro88** [comment]
Changed to "Kirk Rd. and Pine St." to match the "visiting address" at https://www.fnal.gov/pub/contact/index.html in https://github.com/kpedro88/FNAL_ECA_Proposal_Template/commit/5247cabf330a26eec1cfb7c38f8d9bbea8f16f23
